# Generated by Django 3.0.4 on 2020-03-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('annotation', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
            ],
        ),
    ]
